name = "cloudflare-code-assistant-worker"
main = "src/index.ts"
compatibility_date = "2025-01-01"

[ai]
binding = "AI"
remote = true

# Create your own: npx wrangler kv namespace create SESSION_KV
[[kv_namespaces]]
binding = "SESSION_KV"
id = "cf1f06d220144fe6920bf6506102da95"

